version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/wuf
    environment:
      - SOURCE_BRANCH: WUF-41-CI
      - TARGET_BRANCH: gh-pages

    steps:
      #  chekout project
      - checkout

      #  Inspect chekout
      - run:
          command: |
            echo 'Inspecting checkout'
            ls

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      #  Install tools
      - run:
          command: |
            echo 'Installation disabled at the moment'
      # Build application
      - run:
          command: |
            echo 'Build disabled at the moment'
      # Test application
      - run:
          command: |
            echo 'Tests disabled at the moment'
      # Deploy application
      - run:
          command: |
            echo 'Deployment disabled at the moment'
