version: 2.0

jobs:
  build:
    # macos:
    #   xcode: "9.0"
    docker:
      - image: wasvic/node_dev:1.0.0-FM-188-SNAPSHOT
        entrypoint: /bin/sh
    working_directory: ~/wuf
    environment:
      - SOURCE_BRANCH: WUF-41-CI
      - TARGET_BRANCH: gh-pages

    steps:
      # - run:
      #     name: Show the Unix environment
      #     command: |
      #       uname

      #  chekout project
      - checkout

      # TODO Need to find out why this is not working
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     - v1-dependencies-

      - run:
          name: Install tools
          command: |
            # Install headless chrome and place it in the path
            # apk --no-cache upgrade && apk add --no-cache chromium
            # export CHROME_BIN=/usr/lib/chromium
            # printenv

            # Install the application
            yarn bootstrap

      - run:
          name: Build application WUF
          command: |
            # echo 'Building WUF ... it takes a looooooong time'
            yarn build

      - run:
          name: Test application - WUF
          command: |
            # echo 'Testing WUF'
            yarn test

      - run:
          name: Deploy application - WUF
          command: |
            echo 'Deployment disabled at the moment'
