version: 2.1

general:
  branches:
    only:
     - WUF-41-CI # list of branches to build
orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker images

workflows:
    "Hello Workflow":
        triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                  - WUF-41-CI # list of branches to build
        jobs:
          - hello/hello-build
