version: 2.0

jobs:
  build:
    # macos:
    #   xcode: "9.0"
    docker:
      - image: wasvic/node_dev:1.0.0-FM-188-SNAPSHOT
        entrypoint: /bin/sh
    working_directory: ~/wuf
    environment:
      - SOURCE_BRANCH: WUF-41-CI
      - TARGET_BRANCH: gh-pages

    steps:
      #  My unix environment, set up package manager
      - run:
          command: |
            uname

      #  chekout project
      - checkout

      # TODO Need to find out why
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     - v1-dependencies-

      #  Install tools
      - run:
          command: |
            # echo 'Installing tools'
            curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
              && sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
              && apt-get update \
              && apt-get install -y google-chrome-stable build-essential jq git openssh-server \
              && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
            yarn bootstrap

      # Build application
      - run:
          command: |
            # echo 'Building WUF ... it takes a looooooong time'
            yarn build
      # Test application
      - run:
          command: |
            # echo 'Testing WUF'
            yarn test
      # Deploy application
      - run:
          command: |
            echo 'Deployment disabled at the moment'
