version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/project
    environment:
      - SOURCE_BRANCH: WUF-41-CI
      - TARGET_BRANCH: gh-pages

    steps:
      #  Install tools
      - run:
          command: |
            echo 'Installation disabled at the moment'
      # Build application
      - run:
          command: |
            echo 'Build disabled at the moment'
      # Test application
      - run:
          command: |
            echo 'Tests disabled at the moment'
      # Deploy application
      - run:
          command: |
            echo 'Deployment disabled at the moment'
            
